# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Previous JGRGs"
  url = "#past"
  weight = 10

[[main]]
  name = "Invited Speakers"
  url = "#speakers"
  weight = 20

[[main]]
  name = "Programme"
  url = "#programme"
  weight = 30

[[main]]
  name = "Registration"
  url = "#registration"
  weight = 40

[[main]]
  name = "Venue"
  url = "#venue"
  weight = 50

[[main]]
  name = "Accommodation & Travel"
  url = "travel/"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
